/**
 * Curated blocklist of disposable / temporary email providers.
 * Sourced from well-known public lists (Kickbox, disposable-email-domains).
 * Keep entries lowercase, ASCII, no wildcards. Match by exact domain.
 *
 * Admins can extend this list here; a runtime-editable list will land in a
 * later stage. This deliberately stays a small, high-signal set — blocking
 * hundreds of obscure domains hurts more legitimate users than it stops bots
 * (bots move to a fresh domain in minutes; the honeypot + rate limiter
 * catch far more).
 */
export const DISPOSABLE_EMAIL_DOMAINS: ReadonlySet<string> = new Set([
  "0-mail.com","027168.com","10minutemail.com","10minutemail.net","20minutemail.com",
  "2prong.com","30minutemail.com","3d-painting.com","4warding.com","6url.com",
  "anonymbox.com","antichef.com","antichef.net","antispam.de","armyspy.com",
  "beefmilk.com","binkmail.com","bio-muesli.net","bobmail.info","bofthew.com",
  "brefmail.com","bsnow.net","bugmenot.com","bumpymail.com","burnermail.io",
  "byom.de","chogmail.com","choicemail1.com","cool.fr.nf","courriel.fr.nf",
  "curryworld.de","cust.in","dandikmail.com","deadaddress.com","despam.it",
  "devnullmail.com","dfgh.net","digitalsanctuary.com","disbox.net","discard.email",
  "discard.emailnew","discardmail.com","discardmail.de","dispomail.eu","disposable.com",
  "disposable.email","disposableaddress.com","disposableinbox.com","dispose.it",
  "dodgeit.com","dodgit.com","dodsi.com","dontreg.com","dontsendmespam.de",
  "drdrb.net","dumpandjunk.com","dumpmail.de","dumpyemail.com","e4ward.com",
  "email-fake.com","email-temporary.com","email-wegwerf.de","emailigo.de","emailinbox.online",
  "emailondeck.com","emailtemporanea.net","emailtemporario.com.br","emailwarden.com","enterto.com",
  "ephemail.net","fakeinbox.com","fakemail.fr","fakemail.net","fakemailz.com",
  "fansworldwide.de","fastacura.com","fastchevy.com","fasttokens.com","filzmail.com",
  "fivemail.de","fizmail.com","fleckens.hu","fr33mail.info","frapmail.com",
  "front14.org","fudgerub.com","fux0ringduh.com","garliclife.com","gehensiemirnichtaufdensack.de",
  "get2mail.fr","getairmail.com","getmails.eu","getonemail.com","getonemail.net",
  "ghosttexter.de","girlsundertheinfluence.com","gishpuppy.com","gmial.com","goemailgo.com",
  "gowikibooks.com","gowikicampus.com","gowikicars.com","great-host.in","grr.la",
  "guerrillamail.biz","guerrillamail.com","guerrillamail.de","guerrillamail.info","guerrillamail.net",
  "guerrillamail.org","guerrillamailblock.com","harakirimail.com","hidemail.de","hochsitze.com",
  "hoephey.com","hulapla.de","imails.info","incognitomail.com","inoutmail.de",
  "insorg-mail.info","instant-mail.de","instantemailaddress.com","ipoo.org","irish2me.com",
  "jetable.com","jetable.fr.nf","jetable.net","jetable.org","junk1e.com",
  "kaspop.com","kmhow.com","koszmail.pl","kurzepost.de","letthemeatspam.com",
  "lhsdv.com","litedrop.com","lookugly.com","lopl.co.cc","mail-filter.com",
  "mail-temporaire.fr","mail.by","mail4trash.com","mailbucket.org","mailcatch.com",
  "mailde.de","mailde.info","maildrop.cc","maileater.com","mailexpire.com",
  "mailfa.tk","mailforspam.com","mailfreeonline.com","mailguard.me","mailinater.com",
  "mailinator.com","mailinator.net","mailinator.org","mailinator2.com","mailincubator.com",
  "mailismagic.com","mailme.lv","mailmetrash.com","mailmoat.com","mailms.com",
  "mailnesia.com","mailnull.com","mailpick.biz","mailscrap.com","mailshell.com",
  "mailsiphon.com","mailtemp.info","mailtemp.net","mailtome.de","mailtothis.com",
  "mailtrash.net","mailtv.net","mailtv.tv","mailzilla.com","mailzilla.org",
  "mbx.cc","mega.zik.dj","meltmail.com","messagebeamer.de","mierdamail.com",
  "mintemail.com","moburl.com","moncourrier.fr.nf","monemail.fr.nf","monmail.fr.nf",
  "mt2009.com","mycleaninbox.net","mymail-in.net","mypartyclip.de","myphantomemail.com",
  "myspaceinc.com","myspaceinc.net","myspaceinc.org","myspacepimpedup.com","myspamless.com",
  "mytrashmail.com","neomailbox.com","nepwk.com","nervmich.net","nervtmich.net",
  "netmails.com","netmails.net","netzidiot.de","neverbox.com","no-spam.ws",
  "nobulk.com","noclickemail.com","nogmailspam.info","nomail.pw","nomail.xl.cx",
  "nomail2me.com","nospam.wins.com.br","nospam4.us","nospamfor.us","nospammail.net",
  "notmailinator.com","nowmymail.com","nurfuerspam.de","nus.edu.sg","objectmail.com",
  "obobbo.com","odaymail.com","one-time.email","onewaymail.com","onlatedotcom.info",
  "online.ms","oopi.org","ordinaryamerican.net","otherinbox.com","ovpn.to",
  "owlpic.com","pancakemail.com","pjjkp.com","plexolan.de","poczta.onet.pl",
  "politikerclub.de","pookmail.com","privacy.net","proxymail.eu","prtnx.com",
  "putthisinyourspamdatabase.com","qq.com","quickinbox.com","rcpt.at","recode.me",
  "recursor.net","recyclemail.dk","regbypass.com","regbypass.comsafe-mail.net","rejectmail.com",
  "reliable-mail.com","rhyta.com","rmqkr.net","royal.net","rppkn.com",
  "rtrtr.com","s0ny.net","safe-mail.net","safersignup.de","safetymail.info",
  "safetypost.de","sandelf.de","saynotospams.com","selfdestructingmail.com","sendspamhere.com",
  "sharklasers.com","shieldedmail.com","shiftmail.com","shitmail.me","shortmail.net",
  "sibmail.com","skeefmail.com","slaskpost.se","slopsbox.com","smellfear.com",
  "snakemail.com","sneakemail.com","sofimail.com","sofort-mail.de","sogetthis.com",
  "soodonims.com","spam.la","spam.su","spam4.me","spamavert.com",
  "spambob.com","spambob.net","spambob.org","spambog.com","spambog.de",
  "spambog.ru","spambox.info","spambox.irishspringrealty.com","spambox.us","spamcannon.com",
  "spamcannon.net","spamcero.com","spamcon.org","spamcorptastic.com","spamcowboy.com",
  "spamcowboy.net","spamcowboy.org","spamday.com","spamex.com","spamfree24.com",
  "spamfree24.de","spamfree24.eu","spamfree24.info","spamfree24.net","spamfree24.org",
  "spamgoes.com","spamgourmet.com","spamgourmet.net","spamgourmet.org","spamherelots.com",
  "spamhereplease.com","spamhole.com","spamify.com","spaminator.de","spamkill.info",
  "spaml.com","spaml.de","spammotel.com","spamobox.com","spamoff.de",
  "spamsalad.in","spamspot.com","spamthis.co.uk","spamthisplease.com","spamtrail.com",
  "speed.1s.fr","supergreatmail.com","supermailer.jp","suremail.info","svk.jp",
  "sweetxxx.de","tafmail.com","tagyourself.com","talkinator.com","teewars.org",
  "teleworm.com","teleworm.us","temp-mail.com","temp-mail.io","temp-mail.org",
  "temp-mail.ru","tempail.com","tempe-mail.com","tempemail.biz","tempemail.co.za",
  "tempemail.com","tempemail.net","tempinbox.co.uk","tempinbox.com","tempmail.co",
  "tempmail.eu","tempmail.it","tempmail.pp.ua","tempmail.us","tempmail2.com",
  "tempmaildemand.com","tempmailer.com","tempmailer.de","tempomail.fr","tempsky.com",
  "tempthe.net","thanksnospam.info","thankyou2010.com","thecloudindex.com","thisisnotmyrealemail.com",
  "throam.com","throwawayemailaddress.com","throwawaymail.com","tilien.com","tittbit.in",
  "tmail.ws","tmailinator.com","toiea.com","toomail.biz","topranklist.de",
  "tradermail.info","trash-amil.com","trash-mail.at","trash-mail.com","trash-mail.de",
  "trash2009.com","trashdevil.com","trashemail.de","trashinbox.com","trashmail.at",
  "trashmail.com","trashmail.de","trashmail.me","trashmail.net","trashmail.org",
  "trashmail.ws","trashmailer.com","trashymail.com","trashymail.net","tyldd.com",
  "uggsrock.com","upliftnow.com","uplipht.com","uroid.com","us.af",
  "veryrealemail.com","viditag.com","viewcastmedia.com","viewcastmedia.net","viewcastmedia.org",
  "walkmail.net","webemail.me","webm4il.info","weg-werf-email.de","wegwerf-email-addressen.de",
  "wegwerf-emails.de","wegwerfadresse.de","wegwerfemail.com","wegwerfemail.de","wegwerfmail.de",
  "wegwerfmail.info","wegwerfmail.net","wegwerfmail.org","wetrainbayarea.com","wetrainbayarea.org",
  "wh4f.org","whyspam.me","willselfdestruct.com","winemaven.info","wronghead.com",
  "wuzup.net","wuzupmail.net","www.e4ward.com","www.mailinator.com","x24.com",
  "xagloo.com","xemaps.com","xents.com","xmaily.com","xoxy.net",
  "yapped.net","yeah.net","yep.it","yogamaven.com","yopmail.com",
  "yopmail.fr","yopmail.net","ypmail.webarnak.fr.eu.org","zehnminuten.de","zoemail.net",
]);

export function isDisposableEmail(email: string): boolean {
  const at = email.lastIndexOf("@");
  if (at < 0) return false;
  const domain = email.slice(at + 1).toLowerCase();
  return DISPOSABLE_EMAIL_DOMAINS.has(domain);
}
